name: Deploy to DigitalOcean

on:
  push:
    branches:
      - '*'  # Trigger on any branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    env:
      DIGITAL_OCEAN_API_TOKEN: ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      APP_NAME: nota-do-game
      DOMAIN: yourdomain.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images via docker-compose
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/$APP_NAME:${GITHUB_REF_NAME} .

      - name: Push Docker images via docker-compose
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$APP_NAME:${GITHUB_REF_NAME}
          
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
          
      - name: Deploy on DigitalOcean Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITAL_OCEAN_DROPLET_IP }} '
            docker pull $DOCKER_USERNAME/$APP_NAME:${GITHUB_REF_NAME} &&
            docker stop $APP_NAME || true &&
            docker rm $APP_NAME || true &&
            docker run -d --name $APP_NAME -p 80:80 $DOCKER_USERNAME/$APP_NAME:${GITHUB_REF_NAME}
          '

